spring:
  application:
    name: servicio-alumnos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev
server:
  port: 8001
  servlet:
    context-path: /escuela
oauth2:
  clientId: springclient
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST_DB}:${PORT_DB}/alumnoscursos
    username: ${USER_DB}
    password: ${PASS_DB}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${HOST_OAUTH}:8080/realms/springrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://${HOST_EUREKA}:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${HOST_LOCAL}
