
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${HOST_DB}:${PORT_DB}/buscador
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASS_DB}
