spring.application.name=06_microservicio_formacion
server.port=9001
remote.url=http://localhost:8001/escuela/alumnos

remote.user=${REMOTE_USER}
remote.password=${REMOTE_PASS}

oauth2.url=http://localhost:8080/realms/springrealm/protocol/openid-connect/token
oauth2.clientId=springclient
oauth2.grantType=password