spring.application.name=servicio-formacion
server.port=9001
remote.url=http://servicio-alumnos/escuela/alumnos

remote.user=${REMOTE_USER}
remote.password=${REMOTE_PASS}

oauth2.url=http://localhost:8080/realms/springrealm/protocol/openid-connect/token
oauth2.clientId=springclient
oauth2.grantType=password
eureka.client.service-url.defaultZone=http://localhost:8761/eureka